### ISSUE TITLE
Unable to Run Project Locally

### ISSUE THREAD

**Issue by shahilpravind** [Ladvace/Grid-astro-portfolio#8] opened 2024-06-02 14:20 UTC
Hi, template looks great however, I am unable to run it on my local machine. Tested on two different machines (one with Windows 10, another 11) to the same result).

I git cloned the template, ran `npm install`, then `npm run dev` which leads to the following error.

```
> astro-bento-portfolio@0.0.2 dev
> astro dev

02:13:26 [WARN] [config] The feature "assets" is experimental and subject to change (used by @astrojs/netlify).

 astro  v4.9.2 ready in 1697 ms

┃ Local    http://localhost:4321/
┃ Network  use --host to expose

02:13:27 watching for file changes...
02:13:27 [ERROR] [UnhandledRejection] Astro detected an unhandled rejection. Here's the stack trace:
Error: EMFILE: too many open files, open 'D:\...\astro-bento-portfolio\node_modules\zod-to-json-schema\dist\types\parsers\readonly.d.ts'
  Hint:
    Make sure your promises all have an `await` or a `.catch()` handler.
  Error reference:
    https://docs.astro.build/en/reference/errors/unhandled-rejection/
  Stack trace:
    at process.handleUnhandledRejection (file:///D:/.../astro-bento-portfolio/node_modules/astro/dist/vite-plugin-astro-server/plugin.js:43:23)
    at emit (node:internal/process/promises:149:20)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)
```

Any assistance would be appreciated.

**Comment by Ladvace** [comment] 2024-06-02 18:10
Hi, can you tell me what OS you are using? I'm not really able to reproduce it so at the moment it's kinda difficult to fix it

**Comment by shahilpravind** [comment] 2024-06-02 22:46
Tested on 2 machines, one with Windows 11 Pro and another with Windows 10 Home.

**Comment by shahilpravind** [comment] 2024-06-02 23:08
I just tried it with `pnpm` and it worked. 

Tested it with `npm` again and same issue. I think it maybe an `npm `related issue, at least on my end.

**Comment by Ladvace** [comment] 2024-06-03 06:41
I'll try to figure out the problem with npm, for now I'm just gonna close the issue since it seems working at least with npm

**Closed as completed by Ladvace** 2024-06-03 06:41 UTC
